name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Reveal The Guild Secrets
        id: revealed
        uses: the-guild-org/secrets@main
        with:
          gpg-key: ${{ secrets.JOHN_GPG_KEY }}
      - name: Check output
        run: echo ${{ steps.revealed.secrets.COCA_COLA_RECIPE }}
